{% set name = "jupyterlite-terminal" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_terminal-{{ version }}.tar.gz
  sha256: b8022705175faf986b9d1f72a2e9c4622f7c60099ca90aa8f4587d1d8ef6dd86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - jupyterlite_terminal
  requires:
    - jupyterlab =4
    - pip
    - m2-grep  # [win]
    - python {{ python_min }}
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlite/terminal.*OK.*(python, jupyterlite_terminal)"

about:
  home: https://github.com/jupyterlite/terminal
  summary: A terminal for JupyterLite
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ianthomas23
    - jtpio
