{% set name = "jupyterlite-terminal" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_terminal-{{ version }}.tar.gz
  sha256: c9fef2ce25a9b7772c347865a4575e4069de3057ae4f268f412603468da8333f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >=3.8

test:
  imports:
    - jupyterlite_terminal
  requires:
    - jupyterlab =4
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlite/terminal.*OK.*(python, jupyterlite_terminal)"

about:
  home: https://github.com/jupyterlite/terminal
  summary: A terminal for JupyterLite
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ianthomas23
    - jtpio
